[functions.node]
version = 22

[hasura]
adminSecret = "{{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}"
version = "v2.46.0-ce"
webhookSecret = "{{ secrets.NHOST_WEBHOOK_SECRET }}"

[postgres]
version = "14.15-20250311-1"
